#opt_in_rules:
#  - force_unwrapping
#  - empty_count

disabled_rules:
  - function_parameter_count
  - line_length
  - variable_name
  - cyclomatic_complexity
  - nesting
  - operator_whitespace
  - redundant_discardable_let
  - multiple_closures_with_trailing_closure
  - empty_enum_arguments

excluded:
  - Resources
  - Vendor

type_body_length:
  - 700 #warning
  - 1000 #error

file_length:
  - 1000 #warning
  - 1200 #error

function_body_length:
  - 125 #warning
  - 200 #error

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 50

statement_position:
  statement_mode: uncuddled_else

trailing_comma:
  mandatory_comma: true

large_tuple:
  - 4
  - 6
  
custom_rules:
  indentation:
    name: "Indentation"
    message: "Tabs should be used for indentation of lines."
    regex: "(^\t* +\t*)"
    severity: warning
